package at.ac.uibk.sepm.pixplorer.db;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Hibernate entity class for the gpsdata table. Each place has its unique gps 
 * coordinates. The gps data are used to determine if a user has found a place
 * or not.
 * 
 * @author cbo
 */
@Entity
@Table(name = "gpsdata", schema = "public")
public class GPSData implements Serializable {
	private int id;
	private double longitude;	
	private double latitude;
	
	/**
	 * Returns the primary key for this gps data object.
	 * @return primary key
	 */
    @Id
    @SequenceGenerator(name = "gpsdata_id_seq",
            sequenceName = "gpsdata_id_seq",
            allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "gpsdata_id_seq")
    @Column(name = "id", unique = true)
	public int getId() {
		return id;
	}

	/**
	 * Sets the primary key for this gps data object. Do not call this method, the primary
	 * key will be generated by Hibernate!
	 * 
	 * @return primary key - primary key to set
	 */     
	public void setId(int id) {
		this.id = id;
	}	
	
	@Column(name = "longitude")
	public double getLongitude() {
		return longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@Column(name = "latitude")
	public double getLatitude() {
		return latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

}
