package at.ac.uibk.sepm.pixplorer.db;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * Hibernate entity class for the places table. A place is the object that has to be
 * found by any Pixplorer user.
 * 
 * @author cbo
 */
@Entity
@Table(name = "places", schema = "public")
public class Place implements Serializable {
	private int id;
	private String name;
	private String wikiLink;
	private int score;
	private long count;
	private String picture;
	private Category category;
	private GPSData gpsData;
	private long modificationDate;
	private boolean featured;
	
	/**
	 * Constructor.
	 */
	public Place(){
	}
	
	/**
	 * Constructor.
	 * 
	 * @param name - place name
	 * @param wikiLink - link to wiki page
	 * @param picture - Base64 representation of place image
	 * @param category -  category for this place
	 */
	public Place(String name, String wikiLink, long count, String picture, Category category){
		this.name = name;
		this.wikiLink = wikiLink;
		this.count = count;
		this.picture = picture;
		this.category = category;
	}

	/**
	 * Returns the primary key for this place.
	 * @return primary key
	 */	
    @Id
    @SequenceGenerator(name = "places_id_seq",
            sequenceName = "places_id_seq",
            allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "places_id_seq")
    @Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	/**
	 * Sets the primary key for this place. Do not call this method, the primary
	 * key will be generated by Hibernate!
	 * 
	 * @return primary key - primary key to set
	 */      
	public void setId(int id) {
		this.id = id;
	}

	public boolean isFeatured() {
		return featured;
	}
	
	public void setFeatured(boolean featured) {
		this.featured = featured;
	}
	
	@Column(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "wikiLink")
	public String getWikiLink() {
		return wikiLink;
	}

	public void setWikiLink(String wikiLink) {
		this.wikiLink = wikiLink;
	}

	/**
	 * Returns how many users have found this place.
	 * 
	 * @return number of users that have found this place
	 */
	@Column(name = "users_found")
	public long getCount() {
		return count;
	}

	/**
	 * Sets how many users have found this place.
	 * 
	 * @param count - number of users that have found this place
	 */	
	public void setCount(long count) {
		this.count = count;
	}

	/**
	 * Returns a Base64 representation of the image for this place. This image will be
	 * displayed in the Android App.
	 * 
	 * @return image of this place as string
	 */
	@Column(name = "picture")
	public String getPicture() {
		return picture;
	}

	/**
	 * Sets the Base64 representation of the image for this place.
	 * 
	 * @param picture - image of this place as string
	 */	
	public void setPicture(String picture) {
		this.picture = picture;
	}

	@OneToOne
	@OnDelete(action=OnDeleteAction.NO_ACTION)
	@JoinColumn(name = "category")
	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}
	
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "gpsdata")
	public GPSData getGpsData() {
		return gpsData;
	}
	
	public void setGpsData(GPSData gpsData) {
		this.gpsData = gpsData;
	}
	
	@Column(name = "modification_date")
	public long getModificationDate() {
		return modificationDate;
	}
	
	public void setModificationDate(long modificationDate) {
		this.modificationDate = modificationDate;
	}
	
	@Column(name = "score")
	public int getScore() {
		return score;
	}
	
	public void setScore(int score) {
		this.score = score;
	}
}
