package at.ac.uibk.sepm.pixplorer.db;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Hibernate entity class for the trophies table. A trophy is a reward a user
 * can achieve. The trophy contains a SQL statement that specifies the conditions
 * for this trophy. 
 * <p>
 * It stores the Google Play trophy id as well. This id will be 
 * returned to the Android client if a user has achived it and will then be forwarded
 * to Google. 
 * 
 * @author cbo
 */
@Entity
@Table(name = "trophies", schema = "public")
public class Trophy implements Serializable {
	private int id;
	private String name;
	private String description;
	private String code;
	
	/**
	 * Returns the primary key for this trophy.
	 * @return primary key
	 */	
    @Id
    @SequenceGenerator(name = "trophies_id_seq",
            sequenceName = "trophies_id_seq",
            allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "trophies_id_seq")
    @Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}
	
	/**
	 * Sets the primary key for this trophy. Do not call this method, the primary
	 * key will be generated by Hibernate!
	 * 
	 * @return primary key - primary key to set
	 */      
	public void setId(int id) {
		this.id = id;
	}
	
	@Column(name = "name")
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "description")
	public String getDescription() {
		return description;
	}
	
	public void setDescription(String description) {
		this.description = description;
	}
	
	/**
	 * Returns the SQL statement for this trophy.
	 * @return SQL statement
	 */
	@Column(name = "code")
	public String getCode() {
		return code;
	}

	/**
	 * Sets the SQL statement for this trophy.
	 * @param code - SQL statement to set
	 */
	public void setCode(String code) {
		this.code = code;
	}
	
}
